components:
  schemas:
    tmp0:
      properties:
        bios_uuid:
          type: string
        fqdn:
          type: string
        hostname:
          type: string
        id:
          type: string
        ipv4:
          type: string
        ipv6:
          type: string
        mac_address:
          type: string
        netbios_name:
          type: string
        operating_system:
          type: string
        ssh_fingerprint:
          type: string
        system_type:
          type: string
      type: object
    tmp1:
      properties:
        agent_name:
          type: string
        fqdn:
          type: string
        id:
          type: string
        ipv4:
          type: string
        ipv6:
          type: string
        last_seen:
          type: string
        mac_address:
          type: string
        operating_system:
          type: string
      type: object
    tmp2:
      properties:
        hostcount:
          type: string
        name:
          type: string
        owner:
          type: string
        policy:
          type: string
        scan_end:
          type: string
        scan_start:
          type: string
        status:
          type: string
        targets:
          type: string
        uuid:
          type: string
      type: object
    tmp4:
      properties:
        count:
          type: string
        plugin_family:
          type: string
        plugin_name:
          type: string
        severity:
          type: string
        vulnerability_state:
          type: string
      type: object
  securitySchemes: {}
info:
  contact:
    email: frikky@shuffler.io
    name: '@frikkylikeme'
    url: https://twitter.com/frikkylikeme
  description: Automated generation of Tenable Tenable.io
  title: Tenable Tenable.io
  version: 1.0.0
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Returns information about the specified asset.
      parameters:
      - description: The UUID of the asset.
        in: query
        name: Asset UUID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful request
      summary: Tenable.io Asset Info
  tmp1:
    post:
      description: Returns a list of up to 5000 assets.
      parameters: []
      responses:
        '200':
          description: Successful request
      summary: Tenable.io List Assets
  tmp2:
    post:
      description: Returns details for the given scan.
      parameters:
      - description: The ID of the scan.
        in: query
        name: Scan ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful request
      summary: Tenable.io Scan Details
  tmp3:
    post:
      description: Launches a scan.
      parameters:
      - description: The ID of the scan.
        in: body
        name: Scan ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful request
      summary: Tenable.io Scan Launch
  tmp4:
    post:
      description: Retrieves a list of recorded vulnerabilities.
      parameters: []
      responses:
        '200':
          description: Successful request
      summary: Tenable.io Vulnerabilities
