version: '3'
services:
  frontend:
    #build: ./frontend
    image: frikky/shuffle:frontend
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "3001:80"
    networks:
      - shuffle
    restart: unless-stopped
    depends_on:
      - backend
  database:
    #build: ./backend/database
    image: frikky/shuffle:database
    container_name: shuffle-database
    hostname: shuffle-database
    networks:
      - shuffle
    restart: unless-stopped
    volumes:
      - /etc/shuffle:/etc/shuffle
  backend:
    #build: ./backend
    image: frikky/shuffle:backend
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    # Here for debugging:
    ports: 
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    environment: 
      - ORG_ID=${ORG_ID}
      - DATASTORE_EMULATOR_HOST=shuffle-database:8000
    restart: unless-stopped
    depends_on:
      - database
  orborus:
    #build: ./functions/onprem/orborus
    image: frikky/shuffle:orborus
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - ORG_ID=${ORG_ID}
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - BASE_URL=http://${OUTER_HOSTNAME}:${BACKEND_PORT}
    restart: unless-stopped
  app_sdk:
    #build: ./functions/onprem/app_sdk
    image: frikky/shuffle:app_sdk
  worker:
    #build: ./functions/onprem/worker
    image: frikky/shuffle:worker
networks:
  shuffle:
    driver: bridge
